### ISSUE TITLE
preview panel not opening

### ISSUE THREAD

**Issue by sushdg** [harmsk/atom-html-preview#212] opened 2020-04-20 06:39 UTC

**Comment by pannannanna** [comment] 2020-04-21 13:12
Same, I did a fresh install of both atom and the preview package with no luck. The shortcut has no effect on it either

**Comment by sushdg** [comment] 2020-04-21 16:36
Yeah did the same thing! Should we install some preview tool?

**Comment by danleetc** [comment] 2020-04-28 01:33
My preview has stopped working this morning when I tried to resume some  coding. The preview package was working just 5 hours ago. Not sure what has changed overnight....

**Comment by aubreyz** [comment] 2020-05-13 09:40
Related https://github.com/harmsk/atom-html-preview/issues/208

Package not working until updated to work with current javascript packages

**Comment by josiah854** [comment] 2020-05-22 13:45
> Related #208
> 
> Package not working until updated to work with current javascript packages

How and which javascript package do I update?

**Comment by dechen477** [comment] 2020-05-26 17:14
mine also preview is not working at all,, why does it happening so?

**Comment by harmsk** [comment] 2020-05-26 17:27
duplicate of #214

**Closed by harmsk** 2020-05-26 17:27 UTC
