### ISSUE TITLE
Does not work - please! convince me of the contrary

### ISSUE THREAD

**Issue by hironimus76** [harmsk/atom-html-preview#206] opened 2019-11-10 10:36 UTC
Take a look:
https://www.loom.com/share/b4601a8d3f034b4f9e11ff9c68936b1d
Nothing works + no reaction

Is the a solution?
Thanks in advance

**Comment by romain-dartigues** [comment] 2019-11-25 11:39
Duplicate of #182.

**Comment by harmsk** [comment] 2020-01-14 13:41
Closing. Duplicate of #182

**Closed** 2020-01-14 13:41 UTC
