### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by pulkit2012** [harmsk/atom-html-preview#217] opened 2020-05-25 07:09 UTC
HTML-preview not working...blank screen issue

**Comment by booklin** [comment] 2020-05-25 13:05
not working in the atom 1.47.0.   Blank

**Comment by YAACOV2008** [comment] 2020-05-25 15:08
> not working in the atom 1.47.0. Blank
For me as well

**Comment by Atlanta11** [comment] 2020-05-25 19:06
Blank screen in Atom 1.47.0 x64

**Comment by FtsPixel** [comment] 2020-05-25 20:01
Blank screen in Atom 1.47.0 x64

**Comment by nogamesense2** [comment] 2020-05-26 14:49
Blank screen in Atom 1.47.0 x64

**Comment by VisualCreative** [comment] 2020-05-26 15:51
Me too, blanks screen since yesterday in Atom 1.47.0

**Comment by harmsk** [comment] 2020-05-26 17:28
duplicate of #214

**Closed by harmsk** 2020-05-26 17:28 UTC
